services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  wordzle:
    build: .
    depends_on:
      - postgres
  client:
    build: ../client/
  nginx:
    build: ./nginx/
    ports:
      - "5000:5000"
