services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  wordzle:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      telegram_api_token_wordle: "${telegram_api_token_wordle}"
    ports:
      - "8080:8080"
  client:
    build: ../client/
  nginx:
    build: ./nginx/
    ports:
      - "5000:5000"
