spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # 'postgres' if running with compose
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
reset-word-task:
  delay: 300000
  fileLocation: "/wordbank.txt"

bot:
  name: wordle
  token: ${telegram_api_token_wordle}
