spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB} # 'postgres' if running with compose
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
reset-word-task:
  delay: 300000
  fileLocation: "/wordbank.txt"

bot:
  name: wordle
  token: ${telegram_api_token_wordle}
